apiVersion: 1
prune: true
datasources:
  - name: VictoriaMetrics
    uid: inference-lab-vm
    type: prometheus
    access: proxy
    url: http://victoria-metrics:8428
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.48.0
      timeInterval: 5s
