import { useEffect, useMemo, useRef, useState } from "react";

type Status = "enabled" | "disabled" | "unknown";
type Profile = { id: string; label: string; runtime_id: string; model: string; context_length: number | null; gpu_type: string | null; gpu_count: number | null; node_count: number | null; parallelism: Record<"dp"|"tp"|"pp"|"ep", number>; runtime_controls: Record<"prompt_caching"|"chunked_prefill"|"continuous_batching", Status>; gpu_telemetry: string };
type Capabilities = { session: string; profiles: Profile[] };
type Cell = { id: string; label: string; prompt: string; maximum_output_tokens: number };
type Pack = { episode: number; title: string; track: string; objective: string; limitation: string; cells: Cell[] };
type Registry = { classification: string; episodes: Pack[] };
type Stats = { mean: number; p95: number; p99: number };
type Metric = { available: boolean; statistics: Stats | null; unavailable_reason: string | null };
type Lane = { profile_id: string; attempted: number; successful: number; summary: { metrics: Record<string, Metric> } };
type CellState = { state: string; successful: number; attempted: number; ttft: Metric | null; tpot: Metric | null; e2e: Metric | null; interChunk: Metric | null };
type Observation = { cellId: string; profileId: string; attempted: number; successful: number; ttft: Metric | null; tpot: Metric | null; e2e: Metric | null; interChunk: Metric | null };
type EpisodeResult = { gpu_telemetry?: { gpu_utilization_percent?: Metric; gpu_memory_used_mib?: Metric }; [key: string]: unknown };

const emptyCell = (state = "ready"): CellState => ({ state, successful: 0, attempted: 0, ttft: null, tpot: null, e2e: null, interChunk: null });
const episodeFromHash = () => { const value = Number(new URLSearchParams(window.location.hash.split("?")[1] ?? "").get("episode")); return Number.isInteger(value) && value >= 1 && value <= 16 ? value : 1; };
const metricText = (metric: Metric | null, key: keyof Stats, unit = "ms") => metric?.available && metric.statistics ? `${metric.statistics[key].toFixed(1)} ${unit}` : "Unavailable";
function download(value: unknown, episode: number) { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2) + "\n"], { type: "application/json" })); link.download = `episode-${episode}-endpoint-rehearsal.json`; link.click(); URL.revokeObjectURL(link.href); }
function DashboardPanel({ title, value, detail, samples = [], running = false, tone = "safe" }: { title: string; value: string; detail: string; samples?: number[]; running?: boolean; tone?: "safe" | "warning" }) {
  const maximum = Math.max(...samples, 0);
  return <article className="grafana-panel"><header><span>{title}</span><i>{running ? "RUNNING" : samples.length ? "MEASURED" : "NO DATA"}</i></header><strong className={tone}>{value}</strong>{samples.length > 0 && <div className="spark-bars" aria-label={`${samples.length} measured lane-round summaries`}>{samples.slice(-12).map((sample,index) => <b key={index} title={sample.toFixed(1)} style={{height:`${maximum > 0 ? Math.max(8, (sample / maximum) * 100) : 8}%`}} />)}</div>}<small>{detail}</small></article>;
}

export function EpisodeRunner() {
  const [caps, setCaps] = useState<Capabilities | null>(null); const [registry, setRegistry] = useState<Registry | null>(null);
  const [episode, setEpisode] = useState(episodeFromHash); const [profileIds, setProfileIds] = useState<string[]>([]);
  const [suiteRepetitions, setSuiteRepetitions] = useState(5); const [repetitions, setRepetitions] = useState(1); const [batchSize, setBatchSize] = useState(1); const [contextTokens, setContextTokens] = useState(2048); const [sequenceTokens, setSequenceTokens] = useState(128); const [timeout, setTimeoutValue] = useState(120);
  const [running, setRunning] = useState(false); const [runId, setRunId] = useState(""); const [cells, setCells] = useState<Record<string, CellState>>({}); const [observations, setObservations] = useState<Observation[]>([]); const [error, setError] = useState(""); const [result, setResult] = useState<EpisodeResult | null>(null);
  const [suiteRound, setSuiteRound] = useState(0);
  const abort = useRef<AbortController | null>(null); const pack = registry?.episodes.find(item => item.episode === episode);
  const selectedProfiles = useMemo(() => caps?.profiles.filter(item => profileIds.includes(item.id)) ?? [], [caps, profileIds]);
  const requestCount = (pack?.cells.length ?? 0) * profileIds.length * repetitions * suiteRepetitions;
  const episodeConfig = useMemo(() => ({ schema_version: "inference-lab.episode-rehearsal.v1", episode, profile_ids: profileIds, suite_repetitions: suiteRepetitions, repetitions, batch_size: batchSize, context_tokens: contextTokens, sequence_tokens: sequenceTokens, request_timeout_seconds: timeout }), [episode, profileIds, suiteRepetitions, repetitions, batchSize, contextTokens, sequenceTokens, timeout]);

  useEffect(() => { Promise.all([
    fetch("/api/capabilities", { cache: "no-store" }).then(response => response.ok ? response.json() : Promise.reject(new Error(`Capabilities returned ${response.status}`))),
    fetch("/api/episode-suite", { cache: "no-store" }).then(response => response.ok ? response.json() : Promise.reject(new Error(`Episode suite returned ${response.status}`)))
  ]).then(([nextCaps, nextRegistry]: [Capabilities, Registry]) => { setCaps(nextCaps); setRegistry(nextRegistry); setProfileIds(nextCaps.profiles.slice(0, 2).map(item => item.id)); }).catch(failure => setError(failure instanceof Error ? failure.message : "Local bridge unavailable")); }, []);

  const toggleProfile = (id: string) => setProfileIds(current => current.includes(id) ? current.filter(item => item !== id) : current.length < 2 ? [...current, id] : [current[1], id]);
  async function stop() { if (caps && runId) await fetch("/api/cancel", { method: "POST", headers: { "Content-Type": "application/json", "X-Episode1-Session": caps.session }, body: JSON.stringify({ run_id: runId }) }).catch(() => undefined); abort.current?.abort(); setRunning(false); }
  function consume(event: Record<string, unknown>) {
    if (event.type === "accepted") setRunId(String(event.run_id));
    if ((event.type === "suite" || event.type === "cell") && typeof event.suite_round === "number") setSuiteRound(event.suite_round);
    if (event.type === "cell" && typeof event.cell_id === "string") {
      if (event.state === "complete") { const payload = event.result as { lanes: Lane[] }; const next = payload.lanes.map(lane => ({ cellId: event.cell_id as string, profileId: lane.profile_id, attempted: lane.attempted, successful: lane.successful, ttft: lane.summary.metrics.ttft_ms ?? null, tpot: lane.summary.metrics.tpot_ms ?? null, e2e: lane.summary.metrics.e2e_ms ?? null, interChunk: lane.summary.metrics.client_inter_chunk_ms ?? null })); setObservations(current => [...current, ...next]); setCells(current => { const prior = current[event.cell_id as string] ?? emptyCell(); return ({ ...current, [event.cell_id as string]: { ...prior, state: "complete", attempted: prior.attempted + payload.lanes.reduce((sum, item) => sum + item.attempted, 0), successful: prior.successful + payload.lanes.reduce((sum, item) => sum + item.successful, 0) } }); }); }
      else setCells(current => ({ ...current, [event.cell_id as string]: emptyCell(String(event.state)) }));
    }
    if (event.type === "fatal") { setError(String(event.error)); setRunning(false); }
    if (event.type === "complete") { setResult(event.result as EpisodeResult); setRunning(false); }
  }
  async function start() {
    if (!caps || !pack || running || profileIds.length < 1) return;
    setError(""); setResult(null); setRunId(""); setSuiteRound(0); setObservations([]); setCells(Object.fromEntries(pack.cells.map(cell => [cell.id, emptyCell("queued")]))); setRunning(true);
    const controller = new AbortController(); abort.current = controller;
    try {
      const response = await fetch("/api/episode-run", { method: "POST", signal: controller.signal, headers: { "Content-Type": "application/json", "Accept": "text/event-stream", "X-Episode1-Session": caps.session }, body: JSON.stringify(episodeConfig) });
      if (!response.ok) { const body = await response.json(); throw new Error(body.error ?? `Bridge returned ${response.status}`); }
      const reader = response.body?.getReader(); if (!reader) throw new Error("Streaming response is unavailable"); const decoder = new TextDecoder(); let buffer = "";
      while (true) { const { done, value } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); while (buffer.includes("\n\n")) { const index = buffer.indexOf("\n\n"); const frame = buffer.slice(0, index); buffer = buffer.slice(index + 2); const line = frame.split("\n").find(item => item.startsWith("data: ")); if (line) consume(JSON.parse(line.slice(6))); } }
    } catch (failure) { if ((failure as Error).name !== "AbortError") setError(failure instanceof Error ? failure.message : "Episode run failed"); setRunning(false); }
  }
  async function copyCli() { const profiles = profileIds.map(id => `--profile ${id}`).join(" "); await navigator.clipboard.writeText(`scripts/quick-test episode --episode ${episode} ${profiles} --suite-repetitions ${suiteRepetitions} --repetitions ${repetitions} --batch-size ${batchSize} --context-tokens ${contextTokens} --sequence-tokens ${sequenceTokens} --timeout ${timeout}`); }
  const gpuMetric = result?.gpu_telemetry?.gpu_utilization_percent ?? null;
  const gpuMemory = result?.gpu_telemetry?.gpu_memory_used_mib ?? null;
  const metricSamples = (key: "ttft"|"tpot"|"e2e"|"interChunk", percentile: keyof Stats) => observations.flatMap(item => { const metric = item[key]; return metric?.available && metric.statistics ? [metric.statistics[percentile]] : []; });
  const range = (values: number[]) => values.length ? `${Math.min(...values).toFixed(1)}–${Math.max(...values).toFixed(1)} ms` : "Unavailable";
  const ttftP95 = metricSamples("ttft", "p95"), tpotP95 = metricSamples("tpot", "p95"), e2eP99 = metricSamples("e2e", "p99"), interChunkP95 = metricSamples("interChunk", "p95");
  const successful = observations.reduce((sum, item) => sum + item.successful, 0); const attempted = observations.reduce((sum, item) => sum + item.attempted, 0);

  return <article className="episode-runner">
    <header className="runner-hero"><div><p className="lab-eyebrow">EPISODES 01–16 / ENDPOINT REHEARSAL CONSOLE</p><h1>Fire the test pack. Keep the claim honest.</h1><p>Run bounded request packs against one or two endpoints that already exist. This console never creates a pod or changes a runtime.</p></div><div className="diagnostic-stamp"><strong>REHEARSAL ONLY</strong><span>Not canonical episode evidence</span></div></header>
    {error && <div className="quick-alert" role="alert"><strong>{error}</strong></div>}
    <div className="runner-grid"><section className="runner-controls"><label>Episode<select value={episode} disabled={running} onChange={event => { setEpisode(Number(event.target.value)); setCells({}); setResult(null); }}>{registry?.episodes.map(item => <option key={item.episode} value={item.episode}>{String(item.episode).padStart(2,"0")} — {item.title}</option>)}</select></label>
      {pack && <><div className="runner-brief"><span>{pack.track}</span><h2>{pack.title}</h2><p>{pack.objective}</p><strong>{pack.limitation}</strong></div><fieldset><legend>Endpoint profiles · choose one or two</legend>{caps?.profiles.map(profile => <label className={`profile-choice ${profileIds.includes(profile.id) ? "selected" : ""}`} key={profile.id}><input type="checkbox" checked={profileIds.includes(profile.id)} disabled={running} onChange={() => toggleProfile(profile.id)} /><span><b>{profile.label}</b><small>{profile.runtime_id} · {profile.model} · {profile.gpu_type ?? "GPU undeclared"}</small></span></label>)}</fieldset>
      <div className="runner-numbers"><label>Context target · tokens<input type="number" min="1" max="1000000" disabled={running} value={contextTokens} onChange={event => setContextTokens(Number(event.target.value))}/></label><label>Sequence limit · tokens<input type="number" min="1" max="4096" disabled={running} value={sequenceTokens} onChange={event => setSequenceTokens(Number(event.target.value))}/></label><label>Batch / concurrency<input type="number" min="1" max="4" disabled={running} value={batchSize} onChange={event => setBatchSize(Number(event.target.value))}/></label><label>Entire suite repeats<input type="number" min="1" max="10" disabled={running} value={suiteRepetitions} onChange={event => setSuiteRepetitions(Number(event.target.value))}/></label><label>Requests per cell<input type="number" min="1" max="5" disabled={running} value={repetitions} onChange={event => setRepetitions(Number(event.target.value))}/></label><label>Cell timeout · seconds<input type="number" min="1" max="600" disabled={running} value={timeout} onChange={event => setTimeoutValue(Number(event.target.value))}/></label></div>
      <div className="profile-declarations">{selectedProfiles.map(profile => <article key={profile.id}><strong>{profile.runtime_id} / {profile.gpu_type ?? "GPU unknown"}</strong><span>GPU {profile.gpu_count ?? "?"} · nodes {profile.node_count ?? "?"} · DP {profile.parallelism.dp} · TP {profile.parallelism.tp} · PP {profile.parallelism.pp} · EP {profile.parallelism.ep}</span><span>cache {profile.runtime_controls.prompt_caching} · chunked prefill {profile.runtime_controls.chunked_prefill} · continuous batching {profile.runtime_controls.continuous_batching}</span><span>GPU telemetry: {profile.gpu_telemetry}</span></article>)}</div>
      <div className="runner-cost"><strong>{requestCount} bounded requests · round {suiteRound}/{suiteRepetitions}</strong><span>Provider price unavailable · verify externally before paid endpoints</span></div><div className="quick-actions"><button className="start" disabled={!caps || running || profileIds.length < 1} onClick={start}>Run Episode {episode}</button><button className="stop" disabled={!running} onClick={stop}>Stop</button><button onClick={copyCli}>Copy CLI</button><button onClick={() => download(episodeConfig, episode)}>Export config</button>{result && <button onClick={() => download(result, episode)}>Export aggregate</button>}</div></>}
    </section>
    <section className="runner-cells" aria-live="polite"><header><span>TEST CELLS</span><strong>{selectedProfiles.map(item => item.runtime_id).join(" vs ") || "No endpoint selected"}</strong></header>{pack?.cells.map((cell,index) => { const state = cells[cell.id] ?? emptyCell(); const samples = observations.filter(item => item.cellId === cell.id); const values = (key: "ttft"|"tpot"|"e2e"|"interChunk", percentile: keyof Stats) => samples.flatMap(item => { const metric = item[key]; return metric?.available && metric.statistics ? [metric.statistics[percentile]] : []; }); return <article key={cell.id}><span className="cell-index">{String(index + 1).padStart(2,"0")}</span><div><h3>{cell.label}</h3><p>{sequenceTokens} max output tokens · context target {contextTokens}</p>{state.state === "complete" && <dl><div><dt>Requests</dt><dd>{state.successful}/{state.attempted}</dd></div><div><dt>TTFT p95 / p99 ranges</dt><dd>{range(values("ttft","p95"))} / {range(values("ttft","p99"))}</dd></div><div><dt>TPOT p95 / p99 ranges</dt><dd>{range(values("tpot","p95"))} / {range(values("tpot","p99"))}</dd></div><div><dt>E2E p95 / p99 ranges</dt><dd>{range(values("e2e","p95"))} / {range(values("e2e","p99"))}</dd></div><div><dt>Inter-chunk p95 range</dt><dd>{range(values("interChunk","p95"))}</dd></div></dl>}</div><strong className={`cell-state ${state.state}`}>{state.state}</strong></article>; })}<footer><b>ITL boundary</b><p>Metric ranges cover all observed profiles and suite rounds. Inter-chunk latency is captured, but is not claimed as token-level ITL because one SSE content event may contain multiple tokens. Runtime controls and DP/TP/PP/EP are validated profile declarations, not settings this client changes.</p></footer></section></div>
    <section className="grafana-board"><header><div><span>RUN TELEMETRY</span><h2>Operations overview</h2></div><strong>{running ? `Round ${suiteRound}/${suiteRepetitions} · refreshing from stream` : result ? "Run complete" : "Waiting for run"}</strong></header><div className="grafana-grid"><DashboardPanel title="Completed requests" value={attempted ? `${successful}/${attempted}` : "Unavailable"} detail="All observed profiles and suite rounds" running={running}/><DashboardPanel title="TTFT p95 range" value={range(ttftP95)} samples={ttftP95} detail="Range across measured lane-round p95 summaries" running={running}/><DashboardPanel title="TPOT p95 range" value={range(tpotP95)} samples={tpotP95} detail="Range across measured lane-round p95 summaries" running={running}/><DashboardPanel title="E2E p99 range" value={range(e2eP99)} samples={e2eP99} detail="Range across measured lane-round p99 summaries" running={running} tone="warning"/><DashboardPanel title="Client inter-chunk p95 range" value={range(interChunkP95)} samples={interChunkP95} detail="Lane-round cadence proxy; not exact token ITL" running={running}/><DashboardPanel title="GPU utilization" value={metricText(gpuMetric,"mean","%")} detail={gpuMetric?.available ? "Bridge-host nvidia-smi" : "Unavailable from endpoint API"}/><DashboardPanel title="GPU memory" value={metricText(gpuMemory,"mean","MiB")} detail={gpuMemory?.available ? "All visible bridge-host GPUs" : "Unavailable from endpoint API"}/><DashboardPanel title="Error rate" value={attempted ? `${(((attempted-successful)/attempted)*100).toFixed(1)}%` : "Unavailable"} detail="All observed profiles and suite rounds" tone={attempted > successful ? "warning" : "safe"}/></div></section>
  </article>;
}
